name: CICD Build
on:
  push:
    branches:
      - main
      - "*-main"
    tags:
      - "v*"
  pull_request:
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Fetch tags
        run: |
          git fetch --tags --force  # Retrieve annotated tags.
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - name: Build prep
        run: make clean
      - name: Build
        run: make
      - uses: actions/upload-artifact@v4
        with:
          name: bin
          path: bin/
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: bin/*

